### ISSUE TITLE
convert subnet to a igraph object

### ISSUE THREAD

**Issue by duleise** [IOR-Bioinformatics/PCSF#2]
Great work. Almost a one-stop shopping mall for this kind of analysis.
There are still some trivial parameters which I want to control, e.g. title in `plot`, change `Terminal/Steiner` to labels that are relevant to my analysis, etc. I think the most painless way for users is to have a `igraph` object returned from `PCSF*`. I noticed that
```
class(subnet)
[1] "PCSF"   "igraph"
```
Is there any simple way to convert `subnet` to a `igraph` ?
Thank you.

**Comment by murodzhon** [comment]
Thanks for your feedback!

Actually, the `PCSF` and `PCSFe` are derived classes from an `igraph`, so `subnet` inherits all the properties of `igraph` object, you can call and apply any function from `igraph`.

 It is possible to set a legend for the nodes now, we have updated the package.

Thanks!

**Comment by marvas74** [comment]
Yes, but the plotting won't work as for an igraph object as discussed in here (https://github.com/IOR-Bioinformatics/PCSF/issues/1#issuecomment-323739242). So if one could convert the a PCSF object back to being only igraph then one could get the plots to print in anyway one wants.

**Comment by duleise** [comment]
Indeed. Perhaps it's better to keep all the convenient parameters in `plot.PCSF` and let `plot` be `plot`. Similarly, another function name may be needed for `plot` in `plot(res$subnet)`.
This is surely easier said than done. Let me know if I could be of any help.
Thanks again.

**Comment by murodzhon** [comment]
Thanks for the comments and feedback again!

An interactive plotting is more appealing for our package rather than static one to visualize biological networks, therefore we would like to keep `plot.PCSF` and `plot.PCSFe` S3 methods as a main plotting functions. Instead, if you would like to plot with `igraph`, you could use `plot.igraph(subnet)` and `plot.igraph(res$subnet)`. In [(#1 comment)](https://github.com/IOR-Bioinformatics/PCSF/issues/1#issuecomment-323739242), similar approach can be used to plot and save the figure with `igraph`:

```
pdf("x.pdf")
plot.igraph(res$subnet)
dev.off()
```

Thanks!

**Comment by duleise** [comment]
Thank you for your reply.
This works fine.
